version: "3.9"

services:
  transmart:
    build:
        context: ./docker/transmart
        dockerfile: Dockerfile
    user: "${UID}:${GID}"
    working_dir: /app
    volumes:
      - ./src/i18n/locales:/app/src/i18n/locales
      - ./transmart.config.js:/app/transmart.config.js
    environment:
      OPENAI_API_URL: ${OPENAI_API_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}