import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

export default {
	tutorialSidebar: [
		'Introduction',
		{
			type: 'category',
			label: 'Customization',
			items: ['CustomModules', 'CustomTranslator', 'CustomTTS'],
		},
		{
			type: 'category',
			label: 'Guides',
			items: [{ type: 'autogenerated', dirName: 'guides' }],
		},
		{
			type: 'category',
			label: 'API',
			items: [{ type: 'autogenerated', dirName: 'api' }],
		},
		{
			type: 'category',
			label: 'Development',
			items: [{ type: 'autogenerated', dirName: 'dev' }],
		},
	],
} satisfies SidebarsConfig;
