name: Install deps
description: ''
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install packages
      shell: bash
      run: npm install
