name: Site
permissions:
  contents: write
  deployments: write

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted]

# TODO: run only for changes in `site` directory
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-build

      - name: Install deps
        run: npm install

      - name: Build site
        working-directory: "./packages/site"
        run: npm run build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: noreply@example.com
          build_dir: "./packages/site/build"
          branch: gh-pages
