name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init

      - name: Run tests
        run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init

      - name: Lint files
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-build

      - name: Restore third party artifacts
        id: cache-thirdparty-restore
        uses: actions/cache/restore@v4
        with:
          path: ./thirdparty/bergamot/build
          key: ${{ runner.os }}-thirdparty-${{ hashFiles('./thirdparty/bergamot/**') }}

      - name: Compile third party artifacts with docker
        if: steps.cache-thirdparty-restore.outputs.cache-hit != 'true'
        shell: bash
        run: make buildThirdparty

      - name: Save third party artifacts
        id: cache-thirdparty-save
        uses: actions/cache/save@v4
        with:
          path: ./thirdparty/bergamot/build
          key: ${{ steps.cache-thirdparty-restore.outputs.cache-primary-key }}

      - name: Build some targets for test
        run: make prepare buildFirefox buildFirefoxStandalone packAll lintBuilds

      - name: Archive build files
        uses: actions/upload-artifact@v4
        id: upload-build-artifacts
        with:
          name: build-files
          path: build
